# Generated by Django 2.1.2 on 2018-10-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailFyRecord',
            new_name='EmaildFyRond',
        ),
    ]
